(* F5: the HTTPS server must require TLS 1.2 at minimum. This starts an HTTPS
   listener with a self-signed certificate (generated by the cram test). The
   handler is irrelevant: the test only checks the TLS handshake. *)

let respond _vh _config_info _path _request_state =
  Lwt.return
    (Ocsigen.Extensions.Ext_found
       (fun () ->
         Lwt.return
           (Ocsigen.Response.make
              (Cohttp.Response.make ~status:`OK ()))))

let () =
  Ocsigen.Server.start ~ports:[]
    ~ssl_ports:[ (`All, 8453) ]
    ~ssl_info:
      (Some
         { Ocsigen.Config.ssl_certificate = Some "cert.pem"
         ; ssl_privatekey = Some "privkey.pem"
         ; ssl_ciphers = None
         ; ssl_dhfile = None
         ; ssl_curve = None })
    ~logdir:"log" ~datadir:"data" ~uploaddir:None ~usedefaulthostname:true
    ~command_pipe:"local.cmd" ~default_charset:(Some "utf-8")
    [ Ocsigen.Server.host [ respond ] ]
