(* Server for the client timeout tests. The timeout is one second, and the
   server listens both in plain HTTP and over TLS, with a self-signed
   certificate generated by the cram test. It is also given a server timeout,
   which has no effect and should be warned about. Its resources:
   - /slow answers after three seconds, longer than the timeout, the way a comet
     request of Eliom waits for an event before answering;
   - /length reads the whole body of the request and answers its length;
   - anything else answers "ok". *)

open Lwt.Infix

let respond body =
  Lwt.return
    (Ocsigen.Extensions.Ext_found
       (fun () ->
         Lwt.return (Ocsigen.Response.respond_string ~status:`OK ~body ())))

let resources _vh _config_info _path = function
  | Ocsigen.Extensions.Req_found _ ->
      Lwt.return Ocsigen.Extensions.Ext_do_nothing
  | Ocsigen.Extensions.Req_not_found (_, {Ocsigen.Extensions.request_info; _})
    -> (
    match Ocsigen.Request.path request_info with
    | ["slow"] -> Lwt_unix.sleep 3. >>= fun () -> respond "slow response"
    | ["length"] ->
        Cohttp_lwt.Body.to_string (Ocsigen.Request.body request_info)
        >>= fun body -> respond (string_of_int (String.length body))
    | _ -> respond "ok")

let () =
  Ocsigen.Server.start ~client_timeout:1 ~server_timeout:1
    ~ports:[`All, 8076]
    ~ssl_ports:[`All, 8454]
    ~ssl_info:
      (Some
         { Ocsigen.Config.ssl_certificate = Some "cert.pem"
         ; ssl_privatekey = Some "privkey.pem"
         ; ssl_ciphers = None
         ; ssl_dhfile = None
         ; ssl_curve = None })
    ~logdir:"log" ~datadir:"data" ~uploaddir:None ~usedefaulthostname:true
    ~command_pipe:"local.cmd" ~default_charset:(Some "utf-8")
    [Ocsigen.Server.host [resources]]
